### ISSUE TITLE
Contracts no longer auto-refresh

### ISSUE THREAD

**Issue by TheYankeeClipper** [Royal-Modding/FS19_BetterContracts#3]
The only way new contracts appear is a forced "new contracts" action, vs before the most recent update when the majority of contracts appeared on their own via auto-refreshing in the background.

**Comment by TyKonKet** [comment]
That's because we changed how contracts generation behave.
By default about 15 contracts are generated every 12 game hours.
Now 3-7 contracts (based on the amount of fields in the map) are generated every game hour.

**Comment by TheYankeeClipper** [comment]
Is it possible to auto-refresh once per hour or something similar? Otherwise, a contract could be generated but never show, and then be “filled” without the player ever having been aware of its existence in the first place. This is particularly concerning for a contract harvester during harvest season.

**Comment by TyKonKet** [comment]
Sure, we can try to improve it.
I'll keep you updated!

**Comment by TyKonKet** [comment]
Hi @TheYankeeClipper we have released a new beta version in which that issue should be fixed, please give it a try and let us know.
[You can download it here](https://github.com/Royal-Modding/FS19_BetterContracts/releases/tag/1.2.0.0-RC1).

**Comment by mhausberg** [comment]
Hi,
just downloaded and tested successfully (map Ravensburg). In that map, 3 new contracts appear every hour (ingame time).

I myself am halfway through developing a script mod ("SeeContracts"), that tries to put more detail info columns to the contracts menu, like expectedLiters, seed/ fertilizer needed, expected net reward, etc. I also would try to have the list sorted by various columns (e.g. highest net reward first).

Unfortunately, I had to setup my PC from scratch lately, and lost my wip backups. I am just starting to rebuild my lua development / testing environment. I learned a lot last year by looking at sources from GtX-Andy. I really like his orderly, precise, and elegant coding style. What I have seen from your group today, looks at least as good as GtX!

I have only one mod on ModHub yet - [SeeBales](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=142151&title=fs2019). But you inspired me to go back to hackin' again :)

**Comment by TheYankeeClipper** [comment]
> Hi @TheYankeeClipper we have released a new beta version in which that issue should be fixed, please give it a try and let us know.
> [You can download it here](https://github.com/Royal-Modding/FS19_BetterContracts/releases/tag/1.2.0.0-RC1).

I have been using the beta you provided (thank you!) but the original issue still persists on my end. I am playing on Felsbrunn and with a lot of mods; however, the auto-refresh stopped working only after the most recent ModHub update, as I haven’t made other mod changes or additions.

On the flipside, in the previous version after accepting a certain number of contracts (six to eight) there was an issue with “you don’t have access to this land”. This seems to be much more stable now, where I can double that number of accepted contracts and not have access issues.

FWIW, even with auto-refresh not working for me I prefer the latest version because of the additional stability.

**Comment by TyKonKet** [comment]
@TheYankeeClipper I really don't know what to say, I've tested it in many maps (Felsbrunn included) and auto-refresh always worked.
Also no one of our testers nor @mhausberg  noticed that issue...
At the moment I can only suggest to manually refresh them at your needs, keep in mind you can always clear the list to generate new ones, and if you have running contracts they will not be deleted.

**Comment by TheYankeeClipper** [comment]
@TyKonKet I understand. The only thing I can think of is perhaps with the new changes, there is now a conflict with the Harvest Straw at Contracts mod.

I appreciate your efforts. Thank you!
